### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by ahmsaqib**
added to the language list.

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Opening should be lined up

**Comment by ahmsaqib** [comment]
@RhinosF1 I can't edit the file. You edit, please...

**Comment by RhinosF1** [comment]
Use https://github.com/ahmsaqib/landing/blob/patch-2/index.php

**Review by RhinosF1 — APPROVED** [review]

**Comment by RhinosF1** [comment]
Please rebase

**Comment by ahmsaqib** [comment]
I don't understand, explain please

**Comment by RhinosF1** [comment]
You need to update your branch with the latest changes from master

**Comment by RhinosF1** [comment]
You should see a resolve conflicts button on the PR

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Please ensure there are no duplicates in the Lang list and it's in alphabetical order

**Comment by Aftabuzzaman** [comment]
@ahmsaqib এই ফাইল হালনাগাদ করুন। https://github.com/miraheze/landing/blob/master/index.php থেকে এই ফাইলের কোড অনেক ভিন্ন (পুরনো)।

**Comment by paladox** [comment]
BN has been added.

**Pull request closed without merging**
