### PR TITLE
Adjust colors for readability and bring back wave shapes

### PR DESCRIPTION
**Pull request by Xenareee**
Styling changes meant to improve readability and bring back the wave shape that was lost in recent commits.
- Brought back the wave shapes
- Wave shape and overlay images (blobs/map) now use pseudo elements to allow for coloring via CSS. Adjusted their coloring on light mode to be visible
- Added a few global CSS variables to streamline the coloring of multiple elements in dark/light mode
- Adjusted the color of multiple text/link elements to improve readability
- Added a permanent shadow to regular buttons to help visibility
- Added a semitransparent background for header and footer to help the logo look better

### Things I know that still need work (future PRs)
- The middle section needs its colors adjusted to fit the rest of the theme. Currently colors are baked into the images, they need to be treated as masks (like waves/overlays) instead to allow for future color changes.
- Primary color needs to be changed to something more fitting than violet
- All mask styling needs `-webkit-` versions for browser compatibility
- Navigation and colors on mobile need more adjustments - this PR is mostly focused on desktop

## Note
The PR apparently cannot be merged automatically, although I did merge the newest commits into my fork before working on this PR. There shouldn't be any big problems with merging hopefully.

`Edit:` I did change a few things in `index.php`, all related to classes and styling, the main structure is intact. There shouldn't be any issues after keeping  the version from the fork, as the local version works correctly. If any change to this file is unclear feel free to ask and I'll try to explain ^^

### CODE REVIEW

**Comment by Universal-Omega** [comment]
Thank you for the patch, looks good, I will merge once the merge conflicts are resolved.

**Comment by Universal-Omega** [comment]
Hmm, on my device it seems it lost all of its color and background, but that could be cache.

**Comment by Xenareee** [comment]
Displays correctly on two of my devices, likely cache then.

**Comment by Universal-Omega** [comment]
Hmm it seems it works in one of my browsers but not other, it doesn't seem to be cache but rather looking at inspect element the CSS is crossed out, if I had -webkit versions it works fine, so I think we may need webkit compatibility also to make it work cross-browser.

**Comment by Xenareee** [comment]
That makes sense, will add the `-webkit-` versions then in a moment.

**Comment by Xenareee** [comment]
Added, although this PR is now closed. Should I make a new PR, wait for this one to be reopened or even commit directly to `master`?

**Comment by Universal-Omega** [comment]
Add a new PR
Also,
Screenshot_20240206_172913_Chrome
I have just a few more changes I'd suggest (eventually, non urgent, and may be mobile specific, which I am using right now so not sure about desktop)

1) Vertically align the text "Miraheze" with the logo
2) Make the color of the hamburger menu and items not black as black on gray is kinda hard to see.

Just some minor tidbits there, but not to urgent also.

**Comment by Xenareee** [comment]
PR created 👍 (#136)

Yeah, will work on mobile next time.

**Comment by Universal-Omega** [comment]
If you can't tell, CSS is not my strongest area but I came up with something to align wordmark and logo:
```css
.navbar-brand {
  position: relative;
}

.logo {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}

.wordmark {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  left: 80px;
}
```

**Pull request merged**
